---
title: "Titanic"
author: "Nick Miner"
date: "2/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(caret)
library(rpart)
library(rpart.plot)
library(xgboost)
set.seed(0351)
```

```{r}
train_data <- read.csv('train.csv')
test_data <- read.csv('test.csv')
```

```{r}

mr_age <- c()
for(i in 1:length(train_data$Age)){
    if(((grepl("Mr.", train_data$Name[i])) == TRUE) & train_data$Sex[i] == "male"){
      mr_age[[i]] <- train_data$Age[i]
    }
}
mean(na.omit(mr_age))
```

```{r}
mrs_age <- c()
for(i in 1:length(train_data$Age)){
    if(((grepl("Mrs.", train_data$Name[i])) == TRUE) & train_data$Sex[i] == "female"){
      mrs_age[[i]] <- train_data$Age[i]
    }
}
mean(na.omit(mrs_age))
```

```{r}
miss_age <- c()
for(i in 1:length(train_data$Age)){
    if(((grepl("Miss", train_data$Name[i])) == TRUE) & train_data$Sex[i] == "female"){
      miss_age[[i]] <- train_data$Age[i]
    }
}
mean(na.omit(miss_age))
```

```{r}
master_age <- c()
for(i in 1:length(train_data$Age)){
    if(((grepl("Master", train_data$Name[i])) == TRUE) & (train_data$Sex[i] == "male")){
      master_age[[i]] <- train_data$Age[i]
    }
}
mean(na.omit(master_age))
```

```{r}
for (i in 1:length(train_data$Age)) {
  if((grepl("mrs.", tolower(train_data$Name[i]))) & is.na(train_data$Age[i]) & train_data$Sex[i] == "female"){
    train_data$Age[i] <- mean(na.omit(mrs_age))
  }
}

for (i in 1:length(train_data$Age)) {
  if((grepl("mr.", tolower(train_data$Name[i]))) & is.na(train_data$Age[i]) & train_data$Sex[i] == "male"){
    train_data$Age[i] <- mean(na.omit(mr_age))
  }
}

for (i in 1:length(train_data$Age)) {
  if((grepl("miss", tolower(train_data$Name[i]))) & is.na(train_data$Age[i])){
    train_data$Age[i] <- mean(na.omit(miss_age))
  }
}

for (i in 1:length(train_data$Age)) {
  if((grepl("master", tolower(train_data$Name[i]))) & is.na(train_data$Age[i])){
    train_data$Age[i] <- mean(na.omit(master_age))
  }
}

for (i in 1:length(train_data$Age)) {
  if((grepl("dr", tolower(train_data$Name[i]))) & is.na(train_data$Age[i])){
    train_data$Age[i] <- mean(na.omit(mr_age))
  }
}

```

```{r}
train_data$NFamily <- train_data$SibSp + train_data$Parch
test_data$NFamily <- test_data$SibSp + test_data$Parch
```

```{r}
train_data <-train_data[-c(1, 4, 7:12)]
test_data <- test_data[-c(1, 3, 6:11)]
```

```{r}
lm_model <- lm(Survived ~ ., data = train_data)
summary(lm_model)
```

```{r}
dt_model <- rpart(as.factor(Survived) ~ ., data = train_data)
rpart.plot(dt_model)
```

```{r}
train_preds <- predict(dt_model, train_data, type = 'c')
```

```{r}
cm <- confusionMatrix(train_preds,as.factor(train_data$Survived))
cm

#or

dt_accuracy <- sum(diag(table(train_preds, train_data$Survived))) / sum(table(train_preds, train_data$Survived))
dt_accuracy
```

```{r}
test_preds <- predict(dt_model, test_data, type = 'c')
fake_data <- cbind.data.frame(test_data$PassengerId, test_preds)
titanic_submission <- fake_data
names(titanic_submission)[names(titanic_submission)=="test_data$PassengerId"] <- "PassengerId"
names(titanic_submission)[names(titanic_submission)=="test_preds"] <- "Survived"
write.csv(titanic_submission)
```




